name: "Build"

on:
    pull_request:
    push:
      branches:
        - "master"

env:
    COMPOSER_ROOT_VERSION: "0.12.x-dev"

jobs:
    test:
        name: "Reproduce"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2.3.1"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@2.3.1"
              with:
                coverage: "none"
                php-version: "8.0"

            - run: |
                composer install
                php --version
                vendor/bin/php-parse ConstantStringType.php
